PY_TB_VHDL = [ "string_pkg.vhd", "kirsch_synth_pkg.vhd", "kirsch_unsynth_pkg.vhd", "kirsch_tb.vhd" ]
PIN_FILE = /opt-src/CMC/local/maagaard/ece327/lib/pins-NULL.tcl
PY_DESIGN_VHDL = [ "mem.vhd", "kirsch_synth_pkg.vhd", "kirsch.vhd" ]
USER_TOOL_FLAGS = 
PART = EP2C35F672C
DESIGN_ARCH = main
FREQ_MIN = 50
SIM_TOOL = MODELSIM
SH_FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera/altera /opt-src/CMC/local/maagaard/kits-sim/altera/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera/lpm /opt-src/CMC/local/maagaard/kits-sim/altera/cycloneii
ECE327 = /opt-src/CMC/local/maagaard/ece327
SH_TB_VHDL = string_pkg.vhd kirsch_synth_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd
TB_ENTITY = kirsch_tb
GOAL_FREQ = 50
GOAL_PERIOD = 20
RPT_DIR = RPT
PY_FAB_SIM_LIBS = [ "/opt-src/CMC/local/maagaard/kits-sim/altera/altera", "/opt-src/CMC/local/maagaard/kits-sim/altera/altera_mf", "/opt-src/CMC/local/maagaard/kits-sim/altera/lpm", "/opt-src/CMC/local/maagaard/kits-sim/altera/cycloneii" ]
LOGIC_SYNTH_TOOL = PRECISION_RTL
TCL_FAB_SIM_LIBS = { /opt-src/CMC/local/maagaard/kits-sim/altera/altera /opt-src/CMC/local/maagaard/kits-sim/altera/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera/lpm /opt-src/CMC/local/maagaard/kits-sim/altera/cycloneii }
SPEED = 7
GUI_FLAG = -shell
BOARD = DE2
NUM_TIMING_PATHS = 5
PHYS_SYNTH_EXT = vhd
PWR_TOOL = QUARTUS
INTERACTIVE_FLAG = False
TB_ARCH = main
OPT_EFFORT_LOGIC_1 = 0
OPT_EFFORT_LOGIC_2 = 0
DESIGN_ENTITY = kirsch
FAMILY_SHORT = CycloneII
SH_DESIGN_VHDL = mem.vhd kirsch_synth_pkg.vhd kirsch.vhd
ASIC = False
OPT_EFFORT = 0
GENERICS = {  }
LIB_VHDL = 
SH_LIB_VHDL = 
USE_GUI = False
TB_VHDL = string_pkg.vhd, kirsch_synth_pkg.vhd, kirsch_unsynth_pkg.vhd, kirsch_tb.vhd
SIM_SCRIPT = kirsch_tb.sim
FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera/altera, /opt-src/CMC/local/maagaard/kits-sim/altera/altera_mf, /opt-src/CMC/local/maagaard/kits-sim/altera/lpm, /opt-src/CMC/local/maagaard/kits-sim/altera/cycloneii
LOGIC_SYNTH_EXT = v
RPT_TDIR = RPT
FAMILY_LONG = Cyclone II
TCL_DESIGN_VHDL = { mem.vhd kirsch_synth_pkg.vhd kirsch.vhd }
TCL_TB_VHDL = { string_pkg.vhd kirsch_synth_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd }
UWP = kirsch
LC_FAMILY_SHORT = cycloneii
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
TCL_LIB_VHDL = {  }
DESIGN_VHDL = mem.vhd, kirsch_synth_pkg.vhd, kirsch.vhd
PY_LIB_VHDL = []
