FAB_SIM_IP = altera_mf
PY_TB_VHDL = [ "add2_tb.vhd" ]
PY_DESIGN_VHDL = [ "sum.vhd", "carry.vhd", "fulladder.vhd", "add2.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2C35F672C
BOARD = DE2
TCL_TB_VHDL = { add2_tb.vhd }
DESIGN_ENTITY = add2
FAMILY_SHORT = CycloneII
SH_DESIGN_VHDL = sum.vhd carry.vhd fulladder.vhd add2.vhd
DESIGN_ARCH = main
FREQ_MIN = 50
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = /home/ece327
SH_TB_VHDL = add2_tb.vhd
TB_ENTITY = add2_tb
GOAL_FREQ = 250
USE_GUI = True
TB_VHDL = add2_tb.vhd
SIM_SCRIPT = add2_tb.sim
RPT_DIR = RPT
FAB_SIM_HOME = /home/ece327/altera
RPT_TDIR = RPT
FAMILY_LONG = Cyclone II
TCL_DESIGN_VHDL = { sum.vhd carry.vhd fulladder.vhd add2.vhd }
INTERACTIVE_FLAG = True
SPEED = 7
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = add2
TB_ARCH = main
LC_FAMILY_SHORT = cycloneii
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
DESIGN_VHDL = sum.vhd, carry.vhd, fulladder.vhd, add2.vhd
GUI_FLAG = -newgui
