FAB_SIM_IP = altera_mf
PY_DESIGN_VHDL = [ "myflipflop.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2C35F672C
BOARD = DE2
DESIGN_ENTITY = myflipflop
FAMILY_SHORT = CycloneII
SH_DESIGN_VHDL = myflipflop.vhd
DESIGN_ARCH = 
FREQ_MIN = 50
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = /home/ece327
GOAL_FREQ = 250
USE_GUI = True
PHYS_SYNTH_TOOL = QUARTUS
RPT_DIR = RPT
FAB_SIM_HOME = /home/ece327/altera
RPT_TDIR = RPT
FAMILY_LONG = Cyclone II
TCL_DESIGN_VHDL = { myflipflop.vhd }
INTERACTIVE_FLAG = True
DESIGN_VHDL = myflipflop.vhd
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = myflipflop
LC_FAMILY_SHORT = cycloneii
PROG = uw-synth
SPEED = 7
GUI_FLAG = -newgui
